kind: Service

apiVersion: v1

metadata:
    name: flask-app-service
    namespace: flask-app

spec: 
    selector:
        app: flask-app-label

    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
